In [1]:
import numpy as np   # alias 

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [5]:
#  An array object of arbitrary homogeneous items

arr = np.array([1, 2, 3, 4, 5, 6])
arr 

array([1, 2, 3, 4, 5, 6])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6.32])
arr 

array([1.  , 2.  , 3.  , 4.  , 5.  , 6.32])

In [8]:
arr = np.array([1, 2, "salut", 4, 5, 6.32])
arr 

array(['1', '2', 'salut', '4', '5', '6.32'], dtype='<U32')

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6.32])
arr, arr.dtype

(array([1.  , 2.  , 3.  , 4.  , 5.  , 6.32]), dtype('float64'))

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr, arr.dtype

(array([1, 2, 3, 4, 5, 6]), dtype('int64'))

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, True, False])
arr, arr.dtype

(array([1, 2, 3, 4, 5, 6, 1, 0]), dtype('int64'))

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, True, False], dtype=np.int8)
arr, arr.dtype

(array([1, 2, 3, 4, 5, 6, 1, 0], dtype=int8), dtype('int8'))

# Reprezentare pe biți (8 biți = 1 byte)

In [13]:
bin(0)

'0b0'

In [14]:
for i in range(17):
    print("i = ", i, " in binar: ", bin(i))

i =  0  in binar:  0b0
i =  1  in binar:  0b1
i =  2  in binar:  0b10
i =  3  in binar:  0b11
i =  4  in binar:  0b100
i =  5  in binar:  0b101
i =  6  in binar:  0b110
i =  7  in binar:  0b111
i =  8  in binar:  0b1000
i =  9  in binar:  0b1001
i =  10  in binar:  0b1010
i =  11  in binar:  0b1011
i =  12  in binar:  0b1100
i =  13  in binar:  0b1101
i =  14  in binar:  0b1110
i =  15  in binar:  0b1111
i =  16  in binar:  0b10000


In [17]:
bin(2 ** 8 - 1), 2 ** 8 - 1

('0b11111111', 255)

# UINT 8 - 0 .. 255

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, True, False, 255], dtype=np.uint8)
arr, arr.dtype

(array([  1,   2,   3,   4,   5,   6,   1,   0, 255], dtype=uint8),
 dtype('uint8'))

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, True, False, 256], dtype=np.uint8)
arr, arr.dtype

OverflowError: Python integer 256 out of bounds for uint8

# INT8 este intre
# -128 si 127

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, True, False, 127, -128], dtype=np.int8)
arr, arr.dtype

(array([   1,    2,    3,    4,    5,    6,    1,    0,  127, -128],
       dtype=int8),
 dtype('int8'))

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, True, False, 127, -129], dtype=np.int8)
arr, arr.dtype

OverflowError: Python integer -129 out of bounds for int8

In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, True, False, 128, -128], dtype=np.int8)
arr, arr.dtype

OverflowError: Python integer 128 out of bounds for int8

# Fast mathematical operations over arrays

In [25]:
#  An array object of arbitrary homogeneous items

arr = np.array([1, 2, 3, 4, 5, 6])
arr 

array([1, 2, 3, 4, 5, 6])

In [26]:
arr + 3

array([4, 5, 6, 7, 8, 9])

In [27]:
arr ** 2

array([ 1,  4,  9, 16, 25, 36])

In [28]:
arr + arr

array([ 2,  4,  6,  8, 10, 12])

In [29]:

arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([1, 2, 3, 4, 5])
arr1 + arr2 

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

Map - filter - reduce

# 1. Map 

In [30]:
arr = np.array([1, 2, 3, 4, 5, 6])

arr - 3

array([-2, -1,  0,  1,  2,  3])

# 2. Filter

In [31]:
arr = np.array([1, 2, 3, 4, 5, 6])

arr > 3

array([False, False, False,  True,  True,  True])

In [32]:
arr[arr > 3]

array([4, 5, 6])

In [33]:
arr[arr % 2 == 0]

array([2, 4, 6])

# 3. Reduce

In [34]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.sum()

np.int64(21)

In [35]:
arr.mean()

np.float64(3.5)